export const OLFACTORY_FAMILIES = [
  "Floral",
  "Amaderada",
  "Oriental",
  "Cítrica",
  "Fougère",
  "Chipre",
  "Cuero",
  "Gourmand",
  "Acuática",
  "Frutal",
  "Especiada",
  "Aromática",
  "Verde",
  "Almizcle",
];

export const CONCENTRATIONS = [
  "Eau de Cologne (EDC)",
  "Eau de Toilette (EDT)",
  "Eau de Parfum (EDP)",
  "Parfum / Extrait",
  "Elixir",
  "Oil / Attar",
];

export const GENDERS = ["Masculino", "Femenino", "Unisex"];

export const SEASONS = [
  "Primavera",
  "Verano",
  "Otoño",
  "Invierno",
  "Todo el año",
];

export const OCCASIONS = [
  "Diario",
  "Oficina / Trabajo",
  "Cita Romántica",
  "Noche / Fiesta",
  "Gimnasio / Deporte",
  "Evento Especial",
  "Versátil",
];

export const TOP_NOTES = [
  "Bergamota",
  "Bergamota de Calabria",
  "Bergamota de Sicilia",
  "Limón (Lima Ácida)",
  "Limón de Amalfi",
  "Entusiasmo de Limón",
  "Mandarina",
  "Mandarina Verde",
  "Mandarina Siciliana",
  "Naranja",
  "Naranja Italiana",
  "Naranja Tangerina",
  "Pomelo (Toronja)",
  "Cítricos Sicilianos",
  "Lavanda",
  "Menta",
  "Eucalipto",
  "Pimienta Rosa",
  "Jengibre",
  "Cardamomo",
  "Albahaca",
  "Notas Marinas",
  "Notas Verdes",
  "Notas Acuosas",
  "Marihuana (Cannabis)",
  "Pera",
  "Chabacano",
  "Durazno (Melocotón)",
  "Iris de la Toscana",
  "Nuez Moscada",
  "Esclarea",
  "Bayas de Enebro",
  "Azafrán",
  "Grosellas Negras",
  "Especias",
  "Cuero", // Mentioned in "1 Million Parfum" as top note
];

export const HEART_NOTES = [
  "Jazmín",
  "Jazmín Egipcio",
  "Rosa",
  "Rosa de Marruecos",
  "Ylang-Ylang",
  "Geranio",
  "Canela",
  "Nuez Moscada",
  "Iris",
  "Violeta",
  "Hojas de Violeta",
  "Azahar (Flor de Naranjo)",
  "Flor de Azahar del Naranjo",
  "Flor del Naranjo Tunesino",
  "Salvia",
  "Esclarea",
  "Lavanda",
  "Ciruela",
  "Regaliz Negro",
  "Pimienta Negra",
  "Fresa Salvaje",
  "Notas Florales",
  "Cuero",
  "Peonía",
  "Agua de Mar",
  "Enebro de Virginia",
  "Coco",
  "Higo",
  "Sal",
  "Vainilla",
  "Benjuí",
  "Caramelo",
  "Raíz de Lirio",
  "Narciso",
  "Sándalo",
  "Sándalo Blanco",
  "Vetiver de Madagascar",
  "Vetiver de Haití",
  "Amberwood",
  "Hojas de Pachulí",
  "Hojas de Pachulí de Indonesia",
  "Oud Camboyano",
  "Jabón",
  "Mirto",
  "Incienso de Olíbano",
  "Notas Terrosas",
  "Manzana",
  "Humo",
  "Haba Tonka",
];

export const BASE_NOTES = [
  "Sándalo",
  "Cedro",
  "Cedro del Atlas",
  "Vetiver",
  "Pachulí",
  "Vainilla",
  "Vainilla de Madagascar",
  "Ámbar",
  "Ámbar Gris",
  "Almizcle (Musk)",
  "Almizcle Blanco",
  "Almizcle Ambreta",
  "Haba Tonka",
  "Cuero",
  "Oud (Madera de Agar)",
  "Incienso",
  "Benjuí",
  "Musgo",
  "Musgo de Roble",
  "Licor",
  "Notas Minerales",
  "Trufa",
  "Roble",
  "Amberwood",
  "Ambroxan",
  "Ambrofix™",
  "Tabaco",
  "Bálsamo del Perú",
  "Cachemira",
  "Resina",
  "Pino",
  "Nardo",
];
